image: node:latest

stages:
    - build

cache:
    paths:
        - node_modules/

install_deps:
    stage: build
    script:
        - npm install
    artifacts:
        paths:
            - node_modules/
